title: SOMEONE
subtitle: vision
foot: someone © 2022
bei_an: 〇ICP备XXXXXX号
url: http://some.com
robot: robots.txt

pic_cloud_prefix: http://xxx.xxx.com
pic_local: /Users/xxx/xxx
pic_compress_threshold: 10000000
pic_replace_prefix: /Users/xxx

scp_server: xxxcloud
scp_pic_path: /web/test/pic
scp_web_path: /web/test

deploy_auto: true
deploy_interval: 30
